### ISSUE TITLE
Why use obfuscation?

### ISSUE THREAD

**Issue by jpaquit** [machine1337/pdfcrack#1]
Obfuscation is not GPL compatible, please consider abort your obfuscation plan...

**Comment by jpaquit** [comment]
This is not an answer, and it is not even fixed.
In my opinion, nobody should use this piece of s*itware as it does not offer any kind of security.

**Comment by machine1337** [comment]
@jpaquit what kind of security u want?

**Comment by machine1337** [comment]
@jpaquit and it require tools like pdfid, pdf-parser etc...in order to  work? that's why it needs sudo in order to install automatically
