### ISSUE TITLE
./crack.sh: 16: eval: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by manhtetthar** [machine1337/pdfcrack#2]
while i was running crack.sh this error ouucured
./crack.sh: 16: eval: Syntax error: "(" unexpected

**Comment by machine1337** [comment]
commands already given there just type: sudo bash crack.sh

**Comment by jpaquit** [comment]
Is sudo really needed to crack a file?
Don't sudo with a source code you don't know the author or you are not able to audit (like in here with code obfuscation).

**Comment by machine1337** [comment]
@jpaquit as it need sudo because requirements tools will be installed if not found like hashcat, pdfid etc as it needs sudo priv to install
